[theme]
primaryColor = "#F63366"
backgroundColor = "#6E37A9"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
show_github_banner = false

[browser]
gatherUsageStats = false

[global]
showFooter = false
